gandm/language-babel

lib/babel-transpiler.coffee

`require('babel-core')` resolves to the one bundled with Atom, rather than the one installed as a dependency.  If we explicitly load the latter instead, the user can update it more easily when needed (e.g. I use some Babel 5.4 features in my codebase, while Atom ships 5.3.3).

Use the package's own copy of Babel

---

lib/config.coffee

I use `commonStrict` in all of my projects.

add full list of accepted module formatters

---

grammars/Babel Language.json

`language-java` uses `keyword.other.import.java` but `language-javascript` is using `keyword.control.js` so I went with `control`

module keywords are 'control' not 'operator'

---

grammars/Babel Language.json

Currently, javascript classes are getting the classname color as the default color for everything inside them because of `meta.class`. `meta.class.body` is used to reset that back to normal. But even then the opening brace was still getting `meta.class` color until I tagged the braces with `punctuation.section.class`.

fix class braces and class bodies

---

grammars/Babel Language.json

Grammars for other languages seem to just use `meta.function.<language>` but quoting the TextMate manual:
> ...you should re-use the existing names ... You should however append as much information to the sub-type you choose.
so I kept .method as additional information just in case.

syntax themes don't have rules for methods specifically, just functions

---

grammars/Babel Language.json

This is consistent with how `language-javascript-jsx` [does it](https://github.com/subtleGradient/language-javascript-jsx/blob/4209756ea698a281f4176cac7f610af6847c54f0/grammars/JavaScript%20with%20JSX.cson#L23-L39), which is the same as how `language-php` labels [PHP sections in HTML](https://github.com/atom/language-php/blob/59385bb9186ede9c9bb7f788c5f80f2cc206d81a/grammars/php.cson#L33-L51), or `language-ruby` labeling [Ruby in HTML](https://github.com/atom/language-ruby/blob/32cf069f0363558b29918d1fc50039c2d70f38ef/grammars/html%20(ruby%20-%20erb).cson#L69-L94)
Related: https://github.com/atom/one-dark-syntax/issues/42

improve labeling of embedded js section inside jsx

---

grammars/Babel Language.json

The grammar is `Babel ES6 Javascript` although it should be `Babel ES6 JavaScript`.
---
Related issue: https://github.com/Glavin001/atom-preview/issues/108#issuecomment-127642971
I'd prefer to fix the mistyped `Javascript` in `language-babel` instead of switching Atom Preview's usage from `Babel ES6 JavaScript` to using `Javascript` incorrectly as well.
Thanks!

Rename Javascript in grammar to correct language name JavaScript

---

grammars/Babel Language.json

This adds basic support for the jsdoc grammar in doc comments.

Add simple jsdoc grammar support

---

grammars/Babel Language.json

* Add missing `keyword.operator.assignment` in `#literal-function`
* Standardize around `keyword.operator.assignment`
- Since there seems to be precedent for calling it `assignment` instead of `equals` in `#jsx-assignment` and in `#flowtype-parse-operators`.
before and after:
You can find that file at https://github.com/babel/babel-sublime/blob/v8.2.1/samples/js-functions.js
I love the work you've done here! I'm going to port some of it over to babel-sublime :smile:

"keyword.operator.assignment" fixes

---

grammars/Babel Language.json

It seems that atom doesn't care what the type of `applyEndPatternLast` is, so long as it's [truthy](https://github.com/atom/first-mate/commit/610d952f1ecf554594d5cb7b5740824098a4a4d5#diff-51bc0271fadf50c8255c53cc3c01fdb1R13). However, after #80, #81 and this PR, it's then possible using [AAAPackageDev](https://github.com/SublimeText/AAAPackageDev) to convert this syntax definition into a  `tmLanguage` file and have it work with Sublime out-of-the-box :smile: 
@gandm This is change is mostly just for me. It'll make it easier for me to sync changes back-and-forth between language-babel and babel-sublime.

Switch "applyEndPatternLast" type to int

---

grammars/Babel Language.json

The spacing fixes are so subsequent PRs are less noisy. The comments fixes are (selfishly) so when I convert this to YAML, they don't look super weird (e.g. with a double `#`).

Comments and spaces fixes

---

grammars/Babel Language.json

Currently entire variables starting with `$` are receiving the scope `punctuation.dollar.js`.
Anyway, I made it so that `$` is the only part that gets the `punctuation.dollar.js` scope, and the remainder continues to get `variable.other.dollar.js`.
From
```html
<span class="variable other dollar js">
<span class="punctuation dollar js">$variable</span>
</span>
<span class="variable other dollar js">
<span class="punctuation dollar js">$</span>
</span>
```
To
```html
<span class="variable other dollar js">
<span class="punctuation dollar js">$</span>variable
</span>
<span class="variable other dollar js">
<span class="punctuation dollar js">$</span>
</span>
```
Up to you @gandm how want it to be but I'd suggest removing `punctuation.dollar.js` completely as `variable.other.dollar.js` is …

Fix dollar variable scopes

---

grammars/Babel Language.json

I figured a PR would be a good place to start the conversation.
I spend a lot of time customizing my own themes, and sometimes I find it necessary to update the syntax / language grammar. 
Let me know what you think about these changes. Particularly why `literal-constructor` was disabled.

minor updates for theming purposes

---

grammars/Babel Language.json

Hi! It would be nice to recognize `.es` files with language-babel. Babel is [already supporting this extension](https://babeljs.io/docs/usage/require/#usage), and github [just merged](https://github.com/github/linguist/pull/2920) a PR to highlight it as javascript.

Add "es" to allowed fileTypes

---

grammars/Babel Regex.json

Since Atom doesn't seem to have a way to manage priorities, I'm suggesting to remove the filetype here since it conflicts with Facebook's [Reason language](https://github.com/facebook/reason) and I don't think people actually write files just containing a regex.
Would fix facebook/reason#234.

Remove "re" filetype from Regex syntax

---

grammars/Babel Language.json
spec/fixtures/grammar/misc.js

Babel has supported function-bind syntax for a long time, so it would be nice to highlight this syntax in atom.
Please let me know if you found something to fix.
- modify label syntax (`foo: bar`) match strings to ignore double colon (`::`)
- add function-bind syntax token as a literal-operator

add support for function-bind syntax proposal

---

grammars/Babel Language.json
spec/fixtures/grammar/babel-sublime/flow.js
spec/fixtures/grammar/babel-sublime/jsx-es6.jsx
spec/fixtures/grammar/babel-sublime/jsx-full-react-class.jsx
spec/fixtures/grammar/es6module.js
spec/fixtures/grammar/everythingJs/es2015-module.js
spec/fixtures/grammar/misc.js
spec/grammar-spec.coffee

Modify grammar to mark closing quotes properly in import/export module name string literals.
Before:
```javascript
import * from "module-name"
^           ^  punctuation.definition.string.begin.js
```
After:
```javascript
import * from "module-name"
^              punctuation.definition.string.begin.js
^  punctuation.definition.string.end.js
```
This behaviour match other contexts for quotes (and language-javascript grammar)

Fix closing quotes marks in import/export.

---

grammars/Babel Language.json

Since JSX is a materialized UI _data_ and first-class citizen, it can be `yield`'ed from (async) generator.
Here is how the syntax highlighting looks right now:
You can observe the difference in the first line with `yield` and in the line with `return`. Even worse it becames when you use words that are also reserved:

Allow `yield <SomeJSX />` syntax

---

grammars/Babel Language.json

Currently language-babel does not highlight css rules for next case:
This PR should fix this problem.

styled-components: add withConfig method support

---

CHANGELOG.md

The 2.70.1 and 2.70.2 releases were marked as 2.71.1 and 2.71.2 in the change log.

Fix 2.70 release numbers

---

grammars/Babel Language.json

Basically it's been pretty much decided now that `.mjs` as a file extension will be used to determine that a file is a JavaScript module in Node.js (see [here](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md) and [here](https://github.com/nodejs/node/pull/14369)).
Tooling is [already starting to support it](https://github.com/standard-things/esm), so I thought it'd be nice to at least get syntax highlighting on those files.

Added .mjs filetype to recognised file types

---

lib/completions-jsx.coffee

This PR started as just adding the `style` attribute to globally available attributes. The rest have been added on via @mpacer, following the official guide to [supported attributes in React](https://facebook.github.io/react/docs/dom-elements.html#all-supported-html-attributes).

set global attributes for (auto)completion sake

---

lib/transpiler.coffee

Support for plain JS Babel configuration has been added in Babel 7.0.
See the latest blog post:
https://babeljs.io/blog/2017/09/12/planning-for-7.0
... and the related PR:
https://github.com/babel/babel/pull/4892
> PS. I sure hope this is valid Coffee. Not used this language for some time and not sure how to run the test suite. 🤔

Detect .babelrc.js configuration files

---

lib/auto-complete-emmet-css.js
lib/auto-indent.coffee
lib/transpiler.coffee

I've noticed that `language-babel` often contributes ~300ms to activation time. Looking at `atom --profile-startup`, we can see that this is actually due to three big and easily deferrable dependencies:
It's extremely easy to get these out of the startup path by moving the require statements closer to their uses. The three major suspects in the screenshot are:
- `@emmetio/expand-abbreviation` (~60ms)
- `fs-plus` (~80ms)
- `js-yaml` (~150ms)
These are typically lower in practice due to Atom's v8 compile cache, but once these are lazily required `language-babel` consistently takes less than 100ms of activation time according to timecop.

Lazy require some expensive dependencies

---

lib/auto-indent.coffee
spec/auto-indent-spec.coffee

Overview
--------
To better match the behavior of eslint itself, this will no longer throw an error if `.eslintrc` is a directory.
Changes
-------
- Check that candidate eslintrc exists AND is file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gandm/language-babel/470)

fix(indent): ensure eslintrc is a file

---

grammars/Babel Language.json

This changes two things:
1. The setting `limitLineLength` has been replaced by `maxLineLength`. This is then set to 1000, and the related rules that were in effect are deleted because they are now redundant.
2. The property `injectionSelector` is added with a value of `source.embedded.jsx`. This means that when the scope `source.embedded.jsx` is encountered in another file, it will automatically use this packages grammar for the duration of the scope. For example, the scope will be encountered in a markdown file using `language-gfm` if the following is present:
````
```jsx
<jsx code>
```
````

maxLineLength + embedded grammars

---

grammars/Babel Language.json
grammars/Embedded Babel Language.json

Fix #481
This change removes the `injectionSelector` property from the main grammar, which was causing a bug with syntax highlighting being applied to the file.
Instead, it makes a new grammar file called `Embedded Babel Language.json`, which effectively does the same thing as `injectionSelector` but isolates it to an independent grammar. It does not have `name`, `fileTypes`, etc. because it should not appear in the language selection menu or be applied to a file directly. It will however work when the `source.embedded.jsx` scope is reached in another grammar (prime example being in markdown).
The `scopeName` property appears to be necessary (it will not apply without it), but any value besides `source.js.jsx` seems to work. The scope itself does not get applied to the embedded code …

Fix for #481
